---
- name: Create joiner user
  ansible.builtin.user:
    name: joiner
    shell: /bin/bash

- name: Allow joiner user passwordless sudo for the setup_freeipa.sh command
  ansible.builtin.copy:
    content: |
        joiner ALL=(ALL) NOPASSWD: /usr/local/sbin/00_setup_freeipa.sh
    dest: /etc/sudoers.d/joiner
    mode: 0400
    validate: visudo --strict --check --file=%s
