---
- name: Import upgrade playbook
  import_playbook: upgrade.yml

- name: Import python playbook
  import_playbook: python.yml

- name: Install freeipa-client and shadow-utils
  hosts: all
  roles:
    - freeipa_client
  tasks:
    # The Amazon Linux 2 Docker image does not have the groupmod
    # utility installed.
    - name: Install shadow-utils (Amazon)
      package:
        name:
          - shadow-utils
      when: ansible_distribution == 'Amazon'
